spring:
  application:
    name: AREX's Storage Web API Spring Boot
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
    default-property-inclusion: non_null
  profiles:
    active: docker
# for report
arex:
  config:
    # default for application settings
    application:
      provider: ''
      service:
        provider: ''
    default:
      # default for service collect settings
      schedule:
        offsetDays: 1
        sendMaxQps: 20
        targetEnv: ''
      # default for replay schedule settings
      service:
        collect:
          allowDayOfWeeks: 127
          allowTimeOfDayFrom: 00:01
          allowTimeOfDayTo: '23:59'
          sampleRate: 1
          timeMock: true
  prometheus:
    port: 20093