server:
  port: 8093
arex:
  storage:
    cache:
      uri:
    enableDiscoveryEntryPoint: true
  #  mongodbUri: mongodb://arex:iLoveArex@10.3.2.42:27017/arex_storage_db
    recordEnv: PRO
   # categoryTypes:
   #   - name: Hi
   #     entryPoint: true
   #     skipComparison: true